import { cp, rm } from "node:fs/promises";
// These paths are generated by Astro; source content lives in src/ and public/.
for (const path of ["_astro", "files", "images", "photography", "portraits", "resources", "cv", "404.html", "index.html", ".nojekyll"]) {
  await rm(new URL(`../${path}`, import.meta.url), { recursive: true, force: true });
}
await cp(new URL("../dist/", import.meta.url), new URL("../", import.meta.url), { recursive: true });
